{
 "title": "GraphAPI-Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "subscriptions",
    "query": {}
   },
   {
    "name": "LogAnalyticsWorkspaces",
    "label": "LogAnalyticsWorkspaces",
    "query": {}
   },
   {
    "name": "AppId",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 23, "x": 0, "y": 0 },
   "options": {
    "content": "# GraphApi utilization Dashboard\n"
   }
  },
  {
   "title": "GraphApi throttled by AppID",
   "type": "stat",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "basicLogsQuery": false,
      "dashboardTime": true,
      "query": "MicrosoftGraphActivityLogs\r\n| where AppId in (${AppId})\r\n| where ResponseStatusCode == 429\r\n//| where ResponseStatusCode == 500\r\n| summarize Count = count() by AppId , bin(TimeGenerated, 5m)\r\n| project TimeGenerated , AppId , Count\r\n| order by TimeGenerated asc  ",
      "resources": [ "${LogAnalyticsWorkspaces}" ],
      "resultFormat": "time_series",
      "timeColumn": "TimeGenerated"
     }
    }
   ]
  },
  {
   "title": "GraphApi throttled by AppID",
   "type": "table",
   "gridPos": { "h": 9, "w": 10, "x": 13, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "basicLogsQuery": false,
      "dashboardTime": true,
      "query": "// Combine all sign-in tables into one set\r\nlet SignInApps = \r\n    union isfuzzy=true\r\n        (AADNonInteractiveUserSignInLogs | project AppId, AppDisplayName),\r\n        (AADManagedIdentitySignInLogs    | project AppId, ServicePrincipalName),\r\n        (AADServicePrincipalSignInLogs   | project AppId, ServicePrincipalName)\r\n    | summarize AppDisplayName = any(AppDisplayName), ServicePrincipalName = any(ServicePrincipalName) by AppId;\r\nMicrosoftGraphActivityLogs\r\n| where AppId in (${AppId})\r\n| where ResponseStatusCode == 429\r\n| join kind=leftouter SignInApps on AppId\r\n| extend applicationName = strcat(AppDisplayName, ServicePrincipalName)\r\n| summarize Count = count() by AppId, applicationName, bin(TimeGenerated, 5m)\r\n| project TimeGenerated, AppId, applicationName, Count\r\n| order by TimeGenerated asc",
      "resources": [ "${LogAnalyticsWorkspaces}" ],
      "resultFormat": "table",
      "timeColumn": "TimeGenerated"
     }
    }
   ]
  },
  {
   "title": "GraphApi Responce Duration Ms",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    { "panelId": 1 }
   ]
  },
  {
   "title": "GraphApi calls by Path",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "basicLogsQuery": false,
      "dashboardTime": true,
      "query": "MicrosoftGraphActivityLogs\r\n| where AppId in (${AppId})\r\n| extend UriPath = tostring(parse_url(RequestUri).Path)\r\n| summarize Count = count() by UriPath\r\n| order by Count\r\n",
      "resources": [ "${LogAnalyticsWorkspaces}" ],
      "resultFormat": "logs",
      "timeColumn": "TimeGenerated"
     }
    }
   ]
  },
  {
   "title": "GraphApi calls by AppId",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 29 },
   "targets": [
    {
     "azureLogAnalytics": {
      "basicLogsQuery": false,
      "dashboardTime": true,
      "query": "MicrosoftGraphActivityLogs\r\n| where AppId in (${AppId})\r\n| summarize Count = count() by AppId , bin(TimeGenerated, 5m)\r\n| order by TimeGenerated asc  ",
      "resources": [ "${LogAnalyticsWorkspaces}" ],
      "resultFormat": "logs",
      "timeColumn": "TimeGenerated"
     }
    }
   ]
  },
  {
   "title": "GraphApi ResponseStatusCode",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "basicLogsQuery": false,
      "dashboardTime": true,
      "query": "MicrosoftGraphActivityLogs\r\n| where AppId in (${AppId})\r\n| summarize Count = count() by ResponseStatusCode , bin(TimeGenerated, 5m)\r\n| project TimeGenerated , ResponseStatusCode , Count\r\n| order by TimeGenerated asc  ",
      "resources": [ "${LogAnalyticsWorkspaces}" ],
      "resultFormat": "time_series",
      "timeColumn": "TimeGenerated"
     }
    }
   ]
  },
  {
   "title": "Graph API RAW Log",
   "type": "table",
   "gridPos": { "h": 15, "w": 23, "x": 0, "y": 47 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "// Combine all sign-in tables into one set\r\nlet SignInApps = \r\n    union isfuzzy=true\r\n        (AADNonInteractiveUserSignInLogs | project AppId, AppDisplayName),\r\n        (AADManagedIdentitySignInLogs    | project AppId, ServicePrincipalName),\r\n        (AADServicePrincipalSignInLogs   | project AppId, ServicePrincipalName)\r\n    | summarize AppDisplayName = any(AppDisplayName), ServicePrincipalName = any(ServicePrincipalName) by AppId;\r\nMicrosoftGraphActivityLogs\r\n| where AppId in (${AppId})\r\n| join kind=leftouter SignInApps on AppId\r\n| extend ParsedUri = parse_url(RequestUri)\r\n| extend Path = tostring(ParsedUri.Path)\r\n| extend applicationName = strcat(AppDisplayName, ServicePrincipalName)\r\n//| extend PreviousTimeGenerated = next(TimeGenerated)\r\n//| extend IngestDelayInMs = datetime_diff('millisecond', TimeGenerated, PreviousTimeGenerated)",
      "resources": [ "${LogAnalyticsWorkspaces}" ],
      "resultFormat": "logs",
      "timeColumn": "TimeGenerated"
     }
    }
   ]
  },
  {
   "title": "LogAnalytics Diagnostic Data collection insights",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 }
  },
  {
   "title": "Last data update processed ago",
   "type": "gauge",
   "description": "Diagnostics LAW Ingest Delay",
   "gridPos": { "h": 7, "w": 5, "x": 1, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "MicrosoftGraphActivityLogs\r\n| order by TimeGenerated desc\r\n| take 1\r\n| extend LastIngestionRecordDeplyMs = datetime_diff('millisecond', now(), TimeGenerated)\r\n| project LastIngestionRecordDeplyMs",
      "resources": [ "${LogAnalyticsWorkspaces}" ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "Diagnostics LAW Ingest Delay In Ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 22, "x": 1, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } }
  }
 ]
}